### PR TITLE
Remove reference to non-existent README file

### LINKED ISSUE #65: Sktools miss README
README.rst referenced but not present.

### PR DESCRIPTION
**Pull request by vanderhe**
Closes #65.

### CODE REVIEW

**Comment by bhourahine** [comment]
Is this supposed to be merged after #69 ? As distutils seems to be the cause of the failures.

**Comment by vanderhe** [comment]
> Is this supposed to be merged after #69 ? As distutils seems to be the cause of the failures.

Yes please, I only realized #69 after seeing this one fail.

**Comment by vanderhe** [comment]
@bhourahine Rebased on #69.

**Review by bhourahine — APPROVED** [review]
Ready to merge.

**Pull request merged**
